name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch like 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm' # Or 'yarn' or 'pnpm' based on your package manager
          # Add this line to specify the working directory for caching
          cache-dependency-path: 'portfolio/package-lock.json' # Adjust for yarn.lock/pnpm-lock.yaml

      - name: Install dependencies
        run: npm ci # Or yarn install --frozen-lockfile, or pnpm install --frozen-lockfile
        working-directory: ./portfolio # Tell it to run inside the 'portfolio' folder

      - name: Build project
        run: npm run build
        working-directory: ./portfolio # Tell it to run inside the 'portfolio' folder

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          path: './portfolio/dist' # IMPORTANT: The 'dist' folder is inside 'portfolio'
                                  # So the path to the artifacts is './portfolio/dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4